.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-cron-enable - Enable a disabled job


.SH SYNOPSIS
.PP
\fBdotagent cron enable  [flags]\fP


.SH DESCRIPTION
.PP
Enable a disabled job


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH EXAMPLE
.EX
  dotagent cron enable job_abc123
.EE


.SH SEE ALSO
.PP
\fBdotagent-cron(1)\fP
