.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-install - Install a toolpack from local path or GitHub


.SH SYNOPSIS
.PP
\fBdotagent toolpacks install  [flags]\fP


.SH DESCRIPTION
.PP
Install a toolpack from local path or GitHub


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH EXAMPLE
.EX
  dotagent toolpacks install ./examples/toolpacks/github-cli
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
