.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config-validate - Validate active config


.SH SYNOPSIS
.PP
\fBdotagent config validate [flags]\fP


.SH DESCRIPTION
.PP
Validate active config


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-config(1)\fP
