.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-skills-list - List installed skills


.SH SYNOPSIS
.PP
\fBdotagent skills list [flags]\fP


.SH DESCRIPTION
.PP
List installed skills


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH EXAMPLE
.EX
  dotagent skills list
.EE


.SH SEE ALSO
.PP
\fBdotagent-skills(1)\fP
