.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-list - List installed toolpacks


.SH SYNOPSIS
.PP
\fBdotagent toolpacks list [flags]\fP


.SH DESCRIPTION
.PP
List installed toolpacks


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH EXAMPLE
.EX
  dotagent toolpacks list
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
