.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-skills-install - Install a skill from GitHub


.SH SYNOPSIS
.PP
\fBdotagent skills install  [flags]\fP


.SH DESCRIPTION
.PP
Install a skill from GitHub


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH EXAMPLE
.EX
  dotagent skills install dotsetgreg/dotagent-skills/weather
.EE


.SH SEE ALSO
.PP
\fBdotagent-skills(1)\fP
