.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config - Inspect and mutate instance configuration


.SH SYNOPSIS
.PP
\fBdotagent config [flags]\fP


.SH DESCRIPTION
.PP
Inspect and mutate instance configuration


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent(1)\fP, \fBdotagent-config-approve(1)\fP, \fBdotagent-config-history(1)\fP, \fBdotagent-config-path(1)\fP, \fBdotagent-config-rollback(1)\fP, \fBdotagent-config-set(1)\fP, \fBdotagent-config-show(1)\fP, \fBdotagent-config-unset(1)\fP, \fBdotagent-config-validate(1)\fP
