.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-onboard - Initialize ~/.dotagent config and workspace templates


.SH SYNOPSIS
.PP
\fBdotagent onboard [flags]\fP


.SH DESCRIPTION
.PP
Create default configuration and workspace template files for a new dotagent installation.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for onboard


.SH EXAMPLE
.EX
  dotagent onboard
.EE


.SH SEE ALSO
.PP
\fBdotagent(1)\fP
