.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-enable - Enable a toolpack


.SH SYNOPSIS
.PP
\fBdotagent toolpacks enable  [flags]\fP


.SH DESCRIPTION
.PP
Enable a toolpack


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH EXAMPLE
.EX
  dotagent toolpacks enable github-cli
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
