.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-backup - Create and restore instance backups


.SH SYNOPSIS
.PP
\fBdotagent backup [flags]\fP


.SH DESCRIPTION
.PP
Create and restore instance backups


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for backup


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent(1)\fP, \fBdotagent-backup-create(1)\fP, \fBdotagent-backup-restore(1)\fP
