.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-skills-search - List available curated skills


.SH SYNOPSIS
.PP
\fBdotagent skills search [flags]\fP


.SH DESCRIPTION
.PP
List available curated skills


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search


.SH EXAMPLE
.EX
  dotagent skills search
.EE


.SH SEE ALSO
.PP
\fBdotagent-skills(1)\fP
