.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config-unset - Unset/remove a config key


.SH SYNOPSIS
.PP
\fBdotagent config unset  [flags]\fP


.SH DESCRIPTION
.PP
Unset/remove a config key


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for unset


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-config(1)\fP
