.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config-show - Print resolved config


.SH SYNOPSIS
.PP
\fBdotagent config show [flags]\fP


.SH DESCRIPTION
.PP
Print resolved config


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-config(1)\fP
