.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config-history - List config revision history entries


.SH SYNOPSIS
.PP
\fBdotagent config history [flags]\fP


.SH DESCRIPTION
.PP
List config revision history entries


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for history


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-config(1)\fP
