.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-backup-create - Create a .tar.gz backup for the instance


.SH SYNOPSIS
.PP
\fBdotagent backup create [flags]\fP


.SH DESCRIPTION
.PP
Create a .tar.gz backup for the instance


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--output\fP=""
	Backup output path (.tar.gz)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-backup(1)\fP
