.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-skills-remove - Remove an installed skill


.SH SYNOPSIS
.PP
\fBdotagent skills remove  [flags]\fP


.SH DESCRIPTION
.PP
Remove an installed skill


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH EXAMPLE
.EX
  dotagent skills remove weather
.EE


.SH SEE ALSO
.PP
\fBdotagent-skills(1)\fP
