.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-version - Show build/version metadata


.SH SYNOPSIS
.PP
\fBdotagent version [flags]\fP


.SH DESCRIPTION
.PP
Show build/version metadata


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH EXAMPLE
.EX
  dotagent version
.EE


.SH SEE ALSO
.PP
\fBdotagent(1)\fP
