.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-remove - Remove an installed toolpack


.SH SYNOPSIS
.PP
\fBdotagent toolpacks remove  [flags]\fP


.SH DESCRIPTION
.PP
Remove an installed toolpack


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH EXAMPLE
.EX
  dotagent toolpacks remove github-cli
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
