.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-cron-list - List scheduled jobs


.SH SYNOPSIS
.PP
\fBdotagent cron list [flags]\fP


.SH DESCRIPTION
.PP
List scheduled jobs


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH EXAMPLE
.EX
  dotagent cron list
.EE


.SH SEE ALSO
.PP
\fBdotagent-cron(1)\fP
