.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-disable - Disable a toolpack


.SH SYNOPSIS
.PP
\fBdotagent toolpacks disable  [flags]\fP


.SH DESCRIPTION
.PP
Disable a toolpack


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH EXAMPLE
.EX
  dotagent toolpacks disable github-cli
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
