.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks - Manage executable tool packs


.SH SYNOPSIS
.PP
\fBdotagent toolpacks [flags]\fP


.SH DESCRIPTION
.PP
Install, inspect, validate, and doctor executable toolpacks that extend agent capabilities.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for toolpacks


.SH SEE ALSO
.PP
\fBdotagent(1)\fP, \fBdotagent-toolpacks-disable(1)\fP, \fBdotagent-toolpacks-doctor(1)\fP, \fBdotagent-toolpacks-enable(1)\fP, \fBdotagent-toolpacks-install(1)\fP, \fBdotagent-toolpacks-list(1)\fP, \fBdotagent-toolpacks-remove(1)\fP, \fBdotagent-toolpacks-show(1)\fP, \fBdotagent-toolpacks-validate(1)\fP
