.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-skills - Install, remove, search, and inspect skills


.SH SYNOPSIS
.PP
\fBdotagent skills [flags]\fP


.SH DESCRIPTION
.PP
Install, remove, search, and inspect skills


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for skills


.SH SEE ALSO
.PP
\fBdotagent(1)\fP, \fBdotagent-skills-install(1)\fP, \fBdotagent-skills-list(1)\fP, \fBdotagent-skills-remove(1)\fP, \fBdotagent-skills-search(1)\fP, \fBdotagent-skills-show(1)\fP
