.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-cron - Manage scheduled jobs


.SH SYNOPSIS
.PP
\fBdotagent cron [flags]\fP


.SH DESCRIPTION
.PP
Create and manage recurring or cron-expression based jobs for the agent.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cron


.SH SEE ALSO
.PP
\fBdotagent(1)\fP, \fBdotagent-cron-add(1)\fP, \fBdotagent-cron-disable(1)\fP, \fBdotagent-cron-enable(1)\fP, \fBdotagent-cron-list(1)\fP, \fBdotagent-cron-remove(1)\fP
