.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-config-set - Set a config key using dot-path syntax


.SH SYNOPSIS
.PP
\fBdotagent config set   [flags]\fP


.SH DESCRIPTION
.PP
Set a config key using dot-path syntax


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent-config(1)\fP
