.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-toolpacks-validate - Validate all toolpacks or one target


.SH SYNOPSIS
.PP
\fBdotagent toolpacks validate [id] [flags]\fP


.SH DESCRIPTION
.PP
Validate all toolpacks or one target


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for validate


.SH EXAMPLE
.EX
  dotagent toolpacks validate
.EE


.SH SEE ALSO
.PP
\fBdotagent-toolpacks(1)\fP
