.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-gateway - Run native gateway (dev mode only)


.SH SYNOPSIS
.PP
\fBdotagent gateway [flags]\fP


.SH DESCRIPTION
.PP
Start native gateway process for development. Production should use \fBdotagent runtime up\fR\&.


.SH OPTIONS
.PP
\fB-d\fP, \fB--debug\fP[=false]
	Enable debug logging

.PP
\fB--dev\fP[=false]
	Acknowledge native gateway usage for development mode

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for gateway


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent(1)\fP
