.nh
.TH "DOTAGENT" "1" "Feb 2026" "dotagent" ""

.SH NAME
.PP
dotagent-migrate - Migrate legacy ~/.dotagent config/workspace into instance layout


.SH SYNOPSIS
.PP
\fBdotagent migrate [flags]\fP


.SH DESCRIPTION
.PP
Migrate legacy ~/.dotagent config/workspace into instance layout


.SH OPTIONS
.PP
\fB--force\fP[=false]
	Overwrite existing files in target instance when needed

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for migrate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--instance\fP="default"
	Instance ID under ~/.dotagent/instances


.SH SEE ALSO
.PP
\fBdotagent(1)\fP
